# Generated by Django 5.1.5 on 2025-02-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='get_full_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
