# Generated by Django 5.1.5 on 2025-02-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vat_applicable',
            field=models.BooleanField(default=True),
        ),
    ]
