# Generated by Django 5.1.5 on 2025-02-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_vat_applicable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vat_applicable',
        ),
    ]
