# Generated by Django 5.1.5 on 2025-01-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_pricing_tiers_discounttier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_applicable',
            field=models.BooleanField(default=False),
        ),
    ]
