# Generated by Django 5.1.2 on 2025-01-30 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_vat_applicable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
